import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import aws from "../../Assets/Projects/aws.png";
import inclass from "../../Assets/Projects/inclass.png";
import decloud from "../../Assets/Projects/decloud.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={inclass}
              isBlog={false}
              title="InClass Andoid App"
              description="A Student Admin attendance mobile app built using React Native. Used Firebase for user authentication and Firestore for storing data. Student user can scan the QR generated by the Admin user to mark attendance. Admin user will get the list of students who marked their attendance under that UID. Location authentication is applied to restrict any unauthorized attendance."
              ghLink="https://github.com/Coder-Rushabh/inclass"
              demoLink="https://www.youtube.com/watch?si=mXx9pSS64FcmUk3O&v=DgPUneoP2Hg&feature=youtu.be"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={aws}
              isBlog={false}
              title="Cloud Architecture for HA"
              description="Created a VPC that we can use for servers in a production environment. Deployed servers in two Availability Zones using an Auto Scaling group and an Application Load Balancer. For additional security, deployed the servers in a private subnet."
              ghLink="https://github.com/Coder-Rushabh/VPC-with-Public-Private-Subnet"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={decloud}
              isBlog={false}
              title="De Cloud"
              description="A decentralized web application integrates ReactJS for the frontend and Solidity for smart contract development. Utilizing Firebase for authentication,users can securely create accounts, while file uploads to Pinata cloud via the DeCloud app generate unique file hashes stored on a Hardhat-created Blockchain. These hashes verify file authenticity during display."
              ghLink="https://github.com/Coder-Rushabh/De_Cloud"
              demoLink="https://youtu.be/ybM9Wil7Nyk?si=EAGyv3FskJNADBil"              
            />
          </Col>

          
          

         
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
